### ISSUE TITLE
How to modify the mount permissions for Hard Disk

### ISSUE THREAD

**Issue by venkatmakam** [LibreELEC/LibreELEC.tv#8026] opened 2023-08-02 08:32 UTC
### Describe
Hello, i am running nextcloud docker in libreelec. Everything is working fine. Now, I have mounted hard disk in libreelec and trying to access it from nextclound (mounted as volume in docker). But nextcloud could not be able to write into hard disk as drive is accessible only to root user and nextcloud uses www-data as user. Is it possible to mount my hard disk with 777 permissions?

Please provide any other suggestions to access the drive from nextcloud.

### To Reproduce
2. Play '....'
3. See error

### Informations
 - LE Version: [e.g. 11.0.3]
 - Hardware Platform: [e.g. RPi4]

**Comment by heitbaum** [comment] 2023-08-02 08:51
Hi @venkatmakam - I’m going to close this as not a bug. Best to ask on the forums. You should always match your id’s between your containers and host so that “user permissions” can be honored.

**Closed as not planned** 2023-08-02 09:00 UTC
