### ISSUE TITLE
[BUG] Ass subtitle not shown

### ISSUE THREAD

**Issue by rjousse18** [LibreELEC/LibreELEC.tv#5577] opened 2021-08-28 10:38 UTC
### Describe the bug
When i play video with .ass subtitle, I can't see them. Other subtitle type are display correctly

### To Reproduce
1. Play video with ass subtitle

### Informations
 - LE Version: 10.0.0
 - Hardware Platform: RPi4

### Log file
https://paste.kodi.tv/giqemidope.kodi

**Comment by HiassofT** [comment] 2021-08-28 16:17
This seems to be a kodi bug: https://github.com/xbmc/xbmc/issues/20085

I posted some info how to avoid or workaround the issue here on the forum: https://forum.libreelec.tv/thread/23951-libreelec-rpi4-9-95-2-does-not-reproduce-ass-subtitles/?postID=159495#post159495

**Comment by rjousse18** [comment] 2021-08-29 11:19
I'm on 4k TV, when I enable "adjust refresh rate" I have a very small display of the video (with subtitle !) :/ in your solution you said "disable GUI resolution limit", where can i find this option ?

**Comment by chewitt** [comment] 2021-11-26 16:16
Closing as this should have been auto-closed by #5703

**Closed by chewitt** 2021-11-26 16:16 UTC
Labels: BUGFIX, LE 10.0
