### ISSUE TITLE
Missing package from LE mirror

### ISSUE THREAD

**Issue by Yajirove** [LibreELEC/LibreELEC.tv#6866] opened 2022-09-03 13:50 UTC
The following package is missing from the LE mirror and gitlab is currently down for maintenance so LE can not be compiled as the package is not available.

https://github.com/LibreELEC/LibreELEC.tv/blob/97c088f6a15d7b48d4d4d056bdbfdbc91d542155/packages/tools/procps-ng/package.mk#L5

**Comment by SupervisedThinking** [comment] 2022-09-03 18:43
Seems fine to me 🤔 

```
supervisedthinking@x220l:/mnt/dev/LibreELEC-RR$ rm -rf sources/procps-ng
supervisedthinking@x220l:/mnt/dev/LibreELEC-RR$ scripts/get procps-ng
GET      procps-ng (archive)
--2022-09-03 20:42:14--  https://gitlab.com/procps-ng/procps/-/archive/v3.3.17/procps-v3.3.17.tar.bz2
Resolving gitlab.com (gitlab.com)... 172.65.251.78, 2606:4700:90:0:f22e:fbec:5bed:a9b9
Connecting to gitlab.com (gitlab.com)|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: '/mnt/dev/LibreELEC-RR/sources/procps-ng/procps-ng-3.3.17.tar.bz2'

/mnt/dev/LibreELEC-RR/sources/procps-ng/pr     [ <=>                                                                                  ] 932.59K  5.92MB/s    in 0.2s    

2022-09-03 20:42:15 (5.92 MB/s) - '/mnt/dev/LibreELEC-RR/sources/procps-ng/procps-ng-3.3.17.tar.bz2' saved [954968]

    INFO      Calculated checksum: 8374d281f91e5fc9bb9ea8dc991b25331e3a2b0299b46f22c633f7fb6bcb0764
```

**Comment by CvH** [comment] 2022-09-03 20:27
we have currently no mirror script running because nobody knows how the existing one it works

**Comment by heitbaum** [comment] 2022-10-13 07:31
Closing as known issue - I have confirmed all packages for both :libreelec-10.0 and :master branches are currently available as per the PKGURL in the package.my files.

**Closed by heitbaum** 2022-10-13 07:31 UTC
