### ISSUE TITLE
[BUG] No video when libreelec starts before TV starts

### ISSUE THREAD

**Issue by lodesmets** [LibreELEC/LibreELEC.tv#5465] opened 2021-07-03 12:46 UTC
### Describe the bug
When I boot my raspberry pi an afterwards start my tv, I don't get video out. Even when I unplug and plug in the hdmi after they both are started.
But when I first start my tv, and then boot my rpi it works fine

### To Reproduce
1. Install 9.95.5
2. start RPi4
3. Start soundbar (HEOS) and tv

### Informations
 - LE Version:  9.95.5
 - Hardware Platform: RPI4

### Log file
Log from when the problem exists: http://ix.io/3rP7
Log from when I first start the tv: http://ix.io/3rPa

### Additional context
It worked fine when using LE 9.2.X

I have my rpi4 connected to my soundbar, and the soundbar to the tv

**Comment by chewitt** [comment] 2021-07-03 13:53
I'm closing the ticket because this is not a bug, it's the expected behaviour now RPi devices in LE10 no longer use legacy vendor drivers (behaviour is now consistent with other LE devices since ~2012).

Follow the section on Intel GPUs https://wiki.libreelec.tv/configuration/edid and repeat for your RPi4. If you need further support please start a thread in the forums.

**Closed by chewitt** 2021-07-03 13:53 UTC
