### ISSUE TITLE
[BUG] TV show recording crash

### ISSUE THREAD

**Issue by JanHBade** [LibreELEC/LibreELEC.tv#6716] opened 2022-07-18 20:02 UTC
### Describe the bug
Crash loop after playing "bad" TV Show

### To Reproduce
1. Play a "bad" TV Show (artifacts in picture)
2. Kodi crashes and reboot, okay not nice but okay
3. Play another TV show (that is OK) with the same encoding (h264) -> Kodi crashes, NOT okay
4. Play another TV show with different encoding -> works

To make it work I have to reinstall the sd card....

### Informations
 - LE Version: 10.0.2
 - Hardware Platform: RPi4

### Log file
[log-2022-07-18-19.49.25.zip](https://github.com/LibreELEC/LibreELEC.tv/files/9135436/log-2022-07-18-19.49.25.zip)

### Additional context
Logs are from the third step

**Comment by HiassofT** [comment] 2022-07-18 20:32
Please test with the latest LE10 nightly from here https://test.libreelec.tv/10.0/RPi/RPi4/ and post a new log with that build if the issue is still present

**Comment by JanHBade** [comment] 2022-08-16 17:53
I try LibreELEC-RPi4.arm-10.0-nightly-20220813-511ad11.img.gz

the issue is not complete gone but much better

1.  Play a "bad" TV Show, no artifacts but Kodi crashes
2. no auto reboot, hard reboot needed
3. Play another TV show with the same encoding -> works


[log-2022-08-16-17.50.05.zip](https://github.com/LibreELEC/LibreELEC.tv/files/9353250/log-2022-08-16-17.50.05.zip)

**Comment by JanHBade** [comment] 2022-08-16 18:08
oh no nightly is not better, more crashes (without artifacts)
crashes with tv show that are ok -> switch back to stable

[log-2022-08-16-18.07.08.zip](https://github.com/LibreELEC/LibreELEC.tv/files/9353337/log-2022-08-16-18.07.08.zip)

**Comment by heitbaum** [comment] 2023-09-04 12:46
Closing as le10 is no longer being updated. If still and issue in LE11/LE12 - please reopen the issue or reference this issue.

**Closed by heitbaum** 2023-09-04 12:46 UTC
Labels: LE 10.0, RPi
