### ISSUE TITLE
[BUG] Disable internet connectivity check in connman

### ISSUE THREAD

**Issue by jvoisin** [LibreELEC/LibreELEC.tv#5349] opened 2021-05-01 13:54 UTC
### Describe the bug

LibreELEC is using Connman, which does a connectivity check to ipv6.connman.net and ipv4.connman.net every 3 minutes. This "feature" is used to check if the device isn't behind a captive portal, which should super-rarely be the case with LibreELEC. Also, I'm not super-duper at ease with my media center snitching things to intel on a regular basis.
 
It would be nice to disable this behaviour by default by adding the following into `/etc/connman/main.conf`:

```ini
[General]
EnableOnlineCheck=false
```

### To Reproduce
1. Install LibreELEC
2. Monitor DNS queries
3. See that there is at least one query every 3 minutes to ipv6.connman.net or ipv4.connman.net

### Informations

LibreELEC (official): 9.2.6 (RPi4.arm)

**Comment by chewitt** [comment] 2021-05-01 14:11
I'm closing the ticket as this is a feature request not a bug, and this is a bug tracker.

cp /etc/connman/main.conf /storage/.config/connman_main.conf .. edit and reboot

**Closed by chewitt** 2021-05-01 14:11 UTC
