### ISSUE TITLE
IR plugin for KODI

### ISSUE THREAD

**Issue by FSTK-Development** [LibreELEC/LibreELEC.tv#5433] opened 2021-06-12 20:31 UTC
I installed LibreELEC on OPI+2, it works. Thanks!
In the process of using it, 2 questions appeared:
1) Why does the local playlist in the PVR IPTV Simple Client plugin not work? A deleted link to the same playlist works.
2) Will IR sensor support be introduced in LibreELEC? Some devices have a built-in infrared sensor. I hope this feature will someday appear in LibreELEC.

I would like to be able to bind the corresponding IR record from the remote control to the keys. I found 2 solutions for Android and Armbian. Is it possible for such functionality to appear in LibreELEC?
IR for Armbian: https://forum.armbian.com/topic/1953-configuring-orange-pi-pc-to-receive-irinfrared/
IR for Android: http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=541

**Comment by chewitt** [comment] 2021-06-13 00:41
Closing as this is not a bug report. Our support forum for general questions is here: https://forum.libreleec.tv .. thanks.

**Closed by chewitt** 2021-06-13 00:41 UTC
