### ISSUE TITLE
Firefox addon ?

### ISSUE THREAD

**Issue by Qik000** [LibreELEC/LibreELEC.tv#4657] opened 2020-11-14 19:10 UTC
Is there a way to get Firefox on Libreelec ? I dont like Chrome for obvious reasons and i dont want to be contributing to chrome's, and by extension, google's dominance.

**Comment by lrusak** [comment] 2020-11-14 20:21
It's not trivial to compile a browser for an embedded distro. It's not impossible though if someone wants to put the time in.

The other option is through docker.

**Comment by chewitt** [comment] 2020-11-15 00:42
Closing becauss this is not a bug report (what issues are for). Discussion can continue in the forums - there is at least one thread for running FF/Chrome in Docker there IIRC.

**Closed by chewitt** 2020-11-15 00:42 UTC
