### ISSUE TITLE
[BUG] cec broken

### ISSUE THREAD

**Issue by damnms** [LibreELEC/LibreELEC.tv#9003] opened 2024-06-18 08:24 UTC
### Describe the bug

I installed LE12 on a rpi5. I noticed that it does not power on/power off when i power on/power off my TV. Unfortunately this is a killer feature for me, so i switched back to an amlogic device with coreelec. All works here, so its not related to the other devices.

### How to reproduce
1. power off the TV
2. the rpi5 stays on

### Information
 - LibreELEC Version: 12
 - Hardware Platform: rpi5

### Context

https://forum.libreelec.tv/thread/28640-cec-problems-on-rpi5-with-le-nightly/ i started with nightly and from posting 23 i used LE12

**Comment by henning-schild** [comment] 2024-09-05 20:17
seems like a duplicate of #9002

**Comment by damnms** [comment] 2024-09-05 23:17
#9002 is about a not saved configuration. #9003 is that powering off/on the device does just nothing. I am not sure if they are related.

**Comment by heitbaum** [comment] 2024-09-15 03:08
- Closing now that #9254 and #9255 are merged in nightlies. If still an issue please raise on the forum/a bug can be raised.

**Closed by heitbaum** 2024-09-15 03:08 UTC
