### ISSUE TITLE
[BUG] Easy way to view the log is missing

### ISSUE THREAD

**Issue by probonopd** [LibreELEC/LibreELEC.tv#4842] opened 2021-01-03 23:41 UTC
### Describe the bug

An easy way to view the log on the device is missing. Especially when an error occurs, the log should be only one click away in a "Show details..." button.

It is also not easy to find out that one has to ssh into the machine and look at `/storage/.kodi/temp/kodi.log`.

### To Reproduce
1. Open an application ("plugin") that crashes
2. A message tells you to "view the log"
3. It is entirely unclear how to do that, on the device itself (without ssh etc.)

### Informations
 - LE Version: LibreELEC (official): 9.0.2
 - Hardware Platform: Amlogic

**Comment by chewitt** [comment] 2021-01-04 02:55
I'm closing this because LE simply packages Kodi and this is a feature request for better user-experience or ways to read logs on-screen in Kodi not a bug in LE (what this tracker is for). Team Kodi will probably direct you install the log viewer/uploader tool in their add-on repo which does a good job of rendering heavily line-wrapped text containing error messsages that users rarely understand on an inappropriately sized TV screen; or allowing them to pastebin the log file so they can share a URL in forums or review the log in a browser where it's much easier to read. LE has its own log-paste function built into the settings add-on too, if that's easier.

**Closed by chewitt** 2021-01-04 02:55 UTC
