### ISSUE TITLE
[BUG] video calibration limitation

### ISSUE THREAD

**Issue by drunkwolfs** [LibreELEC/LibreELEC.tv#4813] opened 2020-12-30 03:54 UTC
### Describe the bug
how to get around the 480px limit?
The right side of the TV is broken, there is a crack. So I need to get around the calibration limitation.
Tell me which source file it is in. I tried to find it myself but to no avail.

### Informations
 - LE Version: 9.2.6
 - Hardware Platform: RPI3

**Comment by chewitt** [comment] 2021-03-08 14:11
I'm closing the ticket as calibration limts are defined in Kodi code (which we're not going to hack/change) and your TV being cracked is not a bug :)

**Closed by chewitt** 2021-03-08 14:11 UTC
